// Design assets only. Run from the project root: swift assets/branding/render-menu-bar.swift
// The same geometry generates SVG, PNG templates, and the presentation preview.
import AppKit
import Foundation

let output = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
let centers: [(CGFloat, CGFloat)] = [(9, 4.6), (4.6, 9), (13.4, 9), (9, 13.4)]
let stroke: CGFloat = 1.15

func drawMark(in rect: CGRect, color: NSColor) {
    NSGraphicsContext.saveGraphicsState()
    let placement = AffineTransform(
        m11: rect.width / 18, m12: 0, m21: 0, m22: rect.height / 18,
        tX: rect.minX, tY: rect.minY)
    for (x, y) in centers {
        let key = NSBezierPath(roundedRect: CGRect(x: -2.1, y: -2.1, width: 4.2, height: 4.2),
                               xRadius: 0.65, yRadius: 0.65)
        var rotation = AffineTransform()
        rotation.rotate(byDegrees: 45)
        key.transform(using: rotation)
        key.transform(using: AffineTransform(translationByX: x, byY: y))
        key.transform(using: placement)
        key.lineWidth = stroke * rect.width / 18
        key.lineJoinStyle = .round
        color.setStroke()
        key.stroke()
    }
    NSGraphicsContext.restoreGraphicsState()
}

func renderPNG(name: String, size: CGSize, scale: Int, draw: () -> Void) throws {
    guard let bitmap = NSBitmapImageRep(
        bitmapDataPlanes: nil, pixelsWide: Int(size.width) * scale, pixelsHigh: Int(size.height) * scale,
        bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
        colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0),
        let graphics = NSGraphicsContext(bitmapImageRep: bitmap) else {
        throw NSError(domain: "BrandPreview", code: 1,
                      userInfo: [NSLocalizedDescriptionKey: "Cannot create image context"])
    }
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = graphics
    graphics.cgContext.clear(CGRect(x: 0, y: 0, width: bitmap.pixelsWide, height: bitmap.pixelsHigh))
    graphics.cgContext.translateBy(x: 0, y: CGFloat(bitmap.pixelsHigh))
    graphics.cgContext.scaleBy(x: CGFloat(scale), y: -CGFloat(scale))
    graphics.shouldAntialias = true
    draw()
    NSGraphicsContext.restoreGraphicsState()
    guard let data = bitmap.representation(using: .png, properties: [:]) else {
        throw NSError(domain: "BrandPreview", code: 2,
                      userInfo: [NSLocalizedDescriptionKey: "Cannot encode PNG"])
    }
    try data.write(to: output.appendingPathComponent(name), options: .atomic)
}

func color(_ hex: UInt32) -> NSColor {
    NSColor(srgbRed: CGFloat((hex >> 16) & 255) / 255,
            green: CGFloat((hex >> 8) & 255) / 255,
            blue: CGFloat(hex & 255) / 255, alpha: 1)
}

func fill(_ rect: CGRect, _ ink: NSColor, radius: CGFloat = 0) {
    ink.setFill()
    NSBezierPath(roundedRect: rect, xRadius: radius, yRadius: radius).fill()
}

// The canvas is top-down; flip text locally to keep AppKit glyphs upright.
func text(_ value: String, x: CGFloat, y: CGFloat, size: CGFloat,
          weight: NSFont.Weight = .regular, ink: NSColor) {
    let attributes: [NSAttributedString.Key: Any] = [
        .font: NSFont.systemFont(ofSize: size, weight: weight), .foregroundColor: ink
    ]
    let height = (value as NSString).size(withAttributes: attributes).height
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current?.cgContext.translateBy(x: x, y: y + height)
    NSGraphicsContext.current?.cgContext.scaleBy(x: 1, y: -1)
    (value as NSString).draw(at: .zero, withAttributes: attributes)
    NSGraphicsContext.restoreGraphicsState()
}

func symbol(_ name: String, x: CGFloat, y: CGFloat, ink: NSColor) {
    guard let image = NSImage(systemSymbolName: name, accessibilityDescription: nil)?
        .withSymbolConfiguration(.init(pointSize: 13, weight: .medium))?
        .withSymbolConfiguration(.init(paletteColors: [ink])) else { return }
    let fit = min(18 / image.size.width, 18 / image.size.height)
    let width = image.size.width * fit
    let height = image.size.height * fit
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current?.cgContext.translateBy(
        x: x + (18 - width) / 2, y: y + (18 + height) / 2)
    NSGraphicsContext.current?.cgContext.scaleBy(x: 1, y: -1)
    image.draw(in: CGRect(x: 0, y: 0, width: width, height: height))
    NSGraphicsContext.restoreGraphicsState()
}

let svgKeys = centers.map { x, y in
    "  <rect x=\"-2.1\" y=\"-2.1\" width=\"4.2\" height=\"4.2\" rx=\"0.65\" transform=\"translate(\(x) \(y)) rotate(45)\"/>"
}.joined(separator: "\n")
let svg = """
<!-- Generated by swift assets/branding/render-menu-bar.swift. Edit the generator. -->
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
  <title>AppSwitcher four-key diamond menu bar template</title>
  <g fill="none" stroke="#000000" stroke-width="1.15" stroke-linejoin="round">
\(svgKeys)
  </g>
</svg>

"""
try svg.write(to: output.appendingPathComponent("menu-bar-template.svg"), atomically: true, encoding: .utf8)
for scale in [1, 2] {
    try renderPNG(name: scale == 1 ? "menu-bar-template.png" : "menu-bar-template@2x.png",
                  size: CGSize(width: 18, height: 18), scale: scale) {
        drawMark(in: CGRect(x: 0, y: 0, width: 18, height: 18), color: .black)
    }
}

try renderPNG(name: "menu-bar-preview.png", size: CGSize(width: 880, height: 672), scale: 2) {
    let darkInk = color(0x23262D)
    let muted = color(0x686E78)
    fill(CGRect(x: 0, y: 0, width: 880, height: 672), color(0xF2F3F5))
    text("四键 · 菱形", x: 44, y: 32, size: 30, weight: .semibold, ink: darkInk)
    text("AppSwitcher  /  菜单栏线框版", x: 45, y: 76, size: 14, ink: muted)

    fill(CGRect(x: 44, y: 120, width: 386, height: 162), .white, radius: 16)
    fill(CGRect(x: 450, y: 120, width: 386, height: 162), color(0x252830), radius: 16)
    drawMark(in: CGRect(x: 81, y: 157, width: 88, height: 88), color: darkInk)
    drawMark(in: CGRect(x: 487, y: 157, width: 88, height: 88), color: .white)
    text("浅色外观", x: 202, y: 174, size: 19, weight: .medium, ink: darkInk)
    text("单色线框 · 放大细节", x: 202, y: 205, size: 12, ink: muted)
    text("深色外观", x: 608, y: 174, size: 19, weight: .medium, ink: .white)
    text("四键轮廓 · 清晰留白", x: 608, y: 205, size: 12, ink: color(0xBDC2CE))

    for (index, label) in ["浅色菜单栏", "深色菜单栏", "菜单展开时"].enumerated() {
        let y = CGFloat(322 + index * 90)
        let isDark = index == 1
        let ink: NSColor = isDark ? .white : darkInk
        text(label, x: 44, y: y, size: 12, weight: .medium, ink: muted)
        let barY = y + 27
        fill(CGRect(x: 44, y: barY, width: 792, height: 30),
             isDark ? color(0x292C34) : color(0xE3E6EC), radius: 6)
        symbol("apple.logo", x: 62, y: barY + 6, ink: ink)
        text("Finder", x: 98, y: barY + 6, size: 13, weight: .semibold, ink: ink)
        text("文件    编辑    显示    前往    窗口", x: 163, y: barY + 6, size: 13, ink: ink)
        if index == 2 {
            fill(CGRect(x: 566, y: barY + 2, width: 30, height: 26), color(0x707887), radius: 5)
        }
        drawMark(in: CGRect(x: 572, y: barY + 6, width: 18, height: 18),
                 color: index == 2 ? .white : ink)
        symbol("wifi", x: 617, y: barY + 6, ink: ink)
        symbol("battery.100percent", x: 653, y: barY + 6, ink: ink)
        text("周六  9:41", x: 713, y: barY + 6, size: 13, ink: ink)
    }
    text("菜单栏为设计模拟；图形按 18 pt 放置。实际外观由 macOS 模板着色决定。",
         x: 44, y: 610, size: 12, ink: muted)
    text("D1 SELECTED  /  MONOCHROME OUTLINE", x: 44, y: 635, size: 10,
         weight: .medium, ink: muted)
}
print("Generated SVG, 18/36 px PNG templates, and the light/dark/selected preview in \(output.path)")
